require: rt_rubocop_defaults

AllCops:
  TargetRubyVersion: 2.6
  # vendor directory is used by github actions and causes issues if not excluded here
  Exclude:
    - vendor/bundle/**/*

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/*'

Metrics/AbcSize:
  Exclude:
    - test/*

Metrics/ClassLength:
  Exclude:
    - test/*

Metrics/MethodLength:
  Exclude:
    - test/*
