require: rt_rubocop_defaults

AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/*'

Metrics/AbcSize:
  Exclude:
    - test/*

Metrics/ClassLength:
  Exclude:
    - test/*

Metrics/MethodLength:
  Exclude:
    - test/*
